### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by igl** [lttb/is-react-prop#4]
Would you care to publish a browser version of the lib transpiled with babel-env? Or take a PR for it?
Currently you transpile arrow functions (=> edge) but not `const` so it breaks in < IE 11.

**Comment by lttb** [comment]
Yes sure!

**Comment by lttb** [comment]
I'll fix it today, but you are free for PR of course

**Comment by lttb** [comment]
Resolved in v0.1.3
