### ISSUE TITLE
Not compatible with React 16

### ISSUE THREAD

**Issue by hburrows** [lttb/is-react-prop#5]
This package isn't compatible with React 16.  There's a note here https://github.com/cssinjs/styled-jss/issues/37#issuecomment-316928115 suggesting you're working on it.  Is there any timeframe for when this might be fixed?

**Comment by lttb** [comment]
Right, I'm working on the next version here https://github.com/lttb/is-react-prop/pull/3.

So I hope that I'll finish all tests this weekend and release the next version.

**Comment by hburrows** [comment]
Great news and thanks for the quick response.

**Comment by lttb** [comment]
Fixed in https://github.com/lttb/is-react-prop/pull/3
